[tox]
envlist =
    py{38,39,310}-dj32-{postgres},
    py{38,39,310,311,312}-dj41-{postgres},
    py{38,39,310,311,312}-dj42-{postgres},
    py{38,39,310,311,312}-dj{50,51}-{postgres},
    py{310,311,312}-djmain-{postgres},
    docs,
    lint

[gh-actions]
python =
    3.8: py38
    3.9: py39
    3.10: py310
    3.11: py311, docs, lint
    3.12: py312

[gh-actions:env]
DJANGO =
    3.2: dj32
    4.1: dj41
    4.2: dj42
    main: djmain

[testenv]
allowlist_externals = make
deps =
    -rrequirements/test.txt
    py38: psycopg2>=2.9
    py39: psycopg2>=2.9
    py310: psycopg2>=2.9
    py311: psycopg>=3.1,<4
    dj41: psycopg2>=2.9
    py312: psycopg>=3.1,<4
    dj32: Django>=3.2,<3.3
    dj41: Django>=4.1,<4.2
    dj42: Django>=4.2,<4.3
    dj50: Django>=5.0,<5.1
    dj51: Django>=5.1,<5.2
    djmain: https://github.com/django/django/tarball/main

commands =
    postgres: make test
