[tox]
envlist =
    py{38,39,310}-dj32-{postgres},
    py{38,39,310,311,312}-dj41-{postgres},
    py{38,39,310,311,312}-dj42-{postgres},
    py{310,311,312}-djmain-{postgres},
    docs,
    lint

[gh-actions]
python =
    3.8: py38
    3.9: py39
    3.10: py310
    3.11: py311, docs, lint
    3.12: py312

[gh-actions:env]
DJANGO =
    3.2: dj32
    4.1: dj41
    4.2: dj42
    main: djmain

[gh-actions:env]
PSYCOPG =
    2: pspg2
    3: pspg3

[testenv]
allowlist_externals = make
deps =
    -rrequirements/test.txt
    pspg2: psycopg2>=2.9
    pspg3: psycopg>=3.1,<4
    dj32: Django>=3.2,<3.3
    dj41: Django>=4.1,<4.2
    dj42: Django>=4.2,<4.3
    djmain: https://github.com/django/django/tarball/main

commands =
    # sqlite3: coverage run -a runtests.py {posargs}
    # postgres: coverage run -a runtests.py --database=postgres {posargs}
    # mysql: coverage run -a runtests.py --database=mysql {posargs}
    # mariadb: coverage run -a runtests.py --database=mariadb {posargs}
    # coverage report
    postgres: make test

# [testenv:format]
# deps = -rrequirements/lint.txt
# commands =
#     isort docs simple_history runtests.py setup.py
#     black docs simple_history runtests.py setup.py
#     flake8 simple_history

# [testenv:lint]
# deps = pre-commit
# commands =
#     pre-commit run --all-files

# [testenv:docs]
# changedir = docs
# deps = -rrequirements/docs.txt
# commands = sphinx-build -W -b html -d {envtmpdir}/doctrees . {envtmpdir}/html
