# Generated by Django 5.0 on 2023-12-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LegacyModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("test_field", models.CharField(max_length=15)),
            ],
        ),
    ]
