# Generated by Django 5.0 on 2023-12-31 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("legacyapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="legacymodel",
            old_name="test_field",
            new_name="renamed_test_field",
        ),
    ]
