# Generated by Django 5.0 on 2023-12-31 14:53

from django.db import migrations

from strong_migrations import safety_assured


class Migration(migrations.Migration):
    dependencies = [
        ("legacyapp", "0002_rename_test_field"),
    ]

    operations = [
        *safety_assured(
            migrations.RenameField(
                model_name="legacymodel",
                old_name="renamed_test_field",
                new_name="test_field",
            )
        )
    ]
