# Generated by Django 5.0 on 2023-12-31 14:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("legacyapp", "0003_rename_test_field_marked_safe"),
    ]

    operations = [
        migrations.RenameField(
            model_name="legacymodel",
            old_name="test_field",
            new_name="renamed_test_field",
        ),
    ]
